// ============================================
// 미국 주식 종목 매핑 (S&P 500 + 인기 종목)
// 회사명 → 티커 자동 매칭
// ============================================

window.US_STOCKS = {
  // ===== Big Tech =====
  'apple': 'AAPL', 'apple inc': 'AAPL',
  'microsoft': 'MSFT', 'microsoft corp': 'MSFT',
  'nvidia': 'NVDA', 'nvidia corp': 'NVDA', 'nvidia corporation': 'NVDA',
  'alphabet': 'GOOGL', 'google': 'GOOGL', 'alphabet inc': 'GOOGL',
  'amazon': 'AMZN', 'amazon.com': 'AMZN',
  'meta': 'META', 'meta platforms': 'META', 'facebook': 'META',
  'tesla': 'TSLA', 'tesla inc': 'TSLA', 'tesla motors': 'TSLA',
  'netflix': 'NFLX',
  'broadcom': 'AVGO',
  'oracle': 'ORCL',
  'salesforce': 'CRM',
  'adobe': 'ADBE',
  'amd': 'AMD', 'advanced micro devices': 'AMD',
  'intel': 'INTC',
  'qualcomm': 'QCOM',
  'cisco': 'CSCO',
  'ibm': 'IBM', 'international business machines': 'IBM',
  'sap': 'SAP',
  'palantir': 'PLTR',
  'snowflake': 'SNOW',
  'servicenow': 'NOW',
  'workday': 'WDAY',
  'crowdstrike': 'CRWD',
  'palo alto networks': 'PANW',
  'fortinet': 'FTNT',
  'datadog': 'DDOG',
  'mongodb': 'MDB',
  'cloudflare': 'NET',
  'docusign': 'DOCU',
  'zoom': 'ZM', 'zoom video': 'ZM',
  'shopify': 'SHOP',
  'square': 'SQ', 'block': 'SQ',
  'paypal': 'PYPL',
  'roblox': 'RBLX',
  'unity software': 'U', 'unity': 'U',
  'twilio': 'TWLO',
  'roku': 'ROKU',
  'spotify': 'SPOT',
  'snap': 'SNAP',
  'pinterest': 'PINS',
  'reddit': 'RDDT',
  'duolingo': 'DUOL',

  // ===== Semiconductors =====
  'taiwan semiconductor': 'TSM', 'tsmc': 'TSM',
  'asml': 'ASML',
  'micron': 'MU', 'micron technology': 'MU',
  'applied materials': 'AMAT',
  'lam research': 'LRCX',
  'kla': 'KLAC',
  'synopsys': 'SNPS',
  'cadence': 'CDNS',
  'arm': 'ARM', 'arm holdings': 'ARM',
  'marvell': 'MRVL', 'marvell technology': 'MRVL',
  'analog devices': 'ADI',
  'nxp': 'NXPI', 'nxp semiconductors': 'NXPI',
  'on semiconductor': 'ON',
  'microchip': 'MCHP',
  'asm international': 'ASMIY',

  // ===== EV / Auto =====
  'rivian': 'RIVN',
  'lucid': 'LCID', 'lucid motors': 'LCID',
  'ford': 'F', 'ford motor': 'F',
  'general motors': 'GM',
  'toyota': 'TM',
  'honda': 'HMC',
  'stellantis': 'STLA',
  'volkswagen': 'VWAGY',
  'bmw': 'BMWYY',
  'nio': 'NIO',
  'xpeng': 'XPEV',
  'li auto': 'LI',
  'byd': 'BYDDF',

  // ===== Bio / Healthcare =====
  'eli lilly': 'LLY', 'lilly': 'LLY',
  'novo nordisk': 'NVO',
  'pfizer': 'PFE',
  'johnson & johnson': 'JNJ', 'johnson and johnson': 'JNJ',
  'merck': 'MRK',
  'abbvie': 'ABBV',
  'amgen': 'AMGN',
  'moderna': 'MRNA',
  'biontech': 'BNTX',
  'gilead': 'GILD', 'gilead sciences': 'GILD',
  'regeneron': 'REGN',
  'vertex': 'VRTX', 'vertex pharmaceuticals': 'VRTX',
  'biogen': 'BIIB',
  'bristol myers squibb': 'BMY', 'bristol-myers': 'BMY',
  'astrazeneca': 'AZN',
  'novartis': 'NVS',
  'roche': 'RHHBY',
  'sanofi': 'SNY',
  'gsk': 'GSK', 'glaxosmithkline': 'GSK',
  'unitedhealth': 'UNH', 'unitedhealth group': 'UNH',
  'cvs': 'CVS', 'cvs health': 'CVS',
  'humana': 'HUM',
  'cigna': 'CI',
  'elevance health': 'ELV',
  'centene': 'CNC',
  'thermo fisher': 'TMO',
  'danaher': 'DHR',
  'medtronic': 'MDT',
  'stryker': 'SYK',
  'boston scientific': 'BSX',
  'intuitive surgical': 'ISRG',
  'illumina': 'ILMN',
  'abbott': 'ABT', 'abbott laboratories': 'ABT',
  'edwards lifesciences': 'EW',

  // ===== Financial =====
  'jpmorgan': 'JPM', 'jp morgan': 'JPM', 'jpmorgan chase': 'JPM',
  'bank of america': 'BAC',
  'wells fargo': 'WFC',
  'citigroup': 'C',
  'goldman sachs': 'GS',
  'morgan stanley': 'MS',
  'american express': 'AXP', 'amex': 'AXP',
  'visa': 'V',
  'mastercard': 'MA',
  'blackrock': 'BLK',
  'charles schwab': 'SCHW', 'schwab': 'SCHW',
  'fidelity': 'FNF',
  'berkshire hathaway': 'BRK.B',
  'progressive': 'PGR',
  'allstate': 'ALL',
  'metlife': 'MET',
  'aig': 'AIG',
  'prudential': 'PRU',
  'travelers': 'TRV',
  'chubb': 'CB',
  'aflac': 'AFL',
  'pnc': 'PNC', 'pnc financial': 'PNC',
  'us bancorp': 'USB',
  'truist': 'TFC',

  // ===== Energy =====
  'exxon': 'XOM', 'exxonmobil': 'XOM', 'exxon mobil': 'XOM',
  'chevron': 'CVX',
  'shell': 'SHEL',
  'bp': 'BP',
  'totalenergies': 'TTE', 'total': 'TTE',
  'conocophillips': 'COP',
  'eog resources': 'EOG',
  'occidental': 'OXY', 'occidental petroleum': 'OXY',
  'pioneer natural': 'PXD',
  'schlumberger': 'SLB',
  'halliburton': 'HAL',
  'baker hughes': 'BKR',
  'kinder morgan': 'KMI',
  'enbridge': 'ENB',
  'duke energy': 'DUK',
  'nextera energy': 'NEE',
  'southern company': 'SO',
  'dominion energy': 'D',
  'sempra': 'SRE',

  // ===== Consumer =====
  'walmart': 'WMT',
  'costco': 'COST',
  'home depot': 'HD',
  "lowe's": 'LOW', 'lowes': 'LOW',
  'target': 'TGT',
  'kroger': 'KR',
  'mcdonalds': 'MCD', "mcdonald's": 'MCD',
  'starbucks': 'SBUX',
  'chipotle': 'CMG',
  'yum brands': 'YUM',
  'coca-cola': 'KO', 'coca cola': 'KO', 'coke': 'KO',
  'pepsi': 'PEP', 'pepsico': 'PEP',
  'monster': 'MNST', 'monster beverage': 'MNST',
  'procter & gamble': 'PG', 'procter and gamble': 'PG',
  'colgate': 'CL', 'colgate-palmolive': 'CL',
  'unilever': 'UL',
  'estee lauder': 'EL',
  'loreal': 'LRLCY', "l'oreal": 'LRLCY',
  'nike': 'NKE',
  'adidas': 'ADDYY',
  'lululemon': 'LULU',
  'under armour': 'UAA',
  'tjx': 'TJX', 'tj maxx': 'TJX',
  'ross stores': 'ROST',
  'dollar general': 'DG',
  'dollar tree': 'DLTR',
  'best buy': 'BBY',
  'autozone': 'AZO',
  "o'reilly": 'ORLY',
  "carmax": 'KMX',

  // ===== Communication / Media =====
  'disney': 'DIS', 'walt disney': 'DIS',
  'comcast': 'CMCSA',
  'at&t': 'T',
  'verizon': 'VZ',
  't-mobile': 'TMUS',
  'paramount': 'PARA',
  'warner bros': 'WBD', 'warner brothers': 'WBD',
  'fox': 'FOX',
  'electronic arts': 'EA',
  'take two': 'TTWO', 'take-two': 'TTWO',
  'activision blizzard': 'ATVI',

  // ===== Industrial =====
  'general electric': 'GE',
  'ge aerospace': 'GE',
  'caterpillar': 'CAT',
  'deere': 'DE', 'john deere': 'DE',
  'boeing': 'BA',
  'lockheed martin': 'LMT', 'lockheed': 'LMT',
  'raytheon': 'RTX', 'rtx corporation': 'RTX',
  'northrop grumman': 'NOC',
  'general dynamics': 'GD',
  '3m': 'MMM',
  'honeywell': 'HON',
  'emerson electric': 'EMR',
  'illinois tool works': 'ITW',
  'parker hannifin': 'PH',
  'eaton': 'ETN',
  'union pacific': 'UNP',
  'csx': 'CSX',
  'norfolk southern': 'NSC',
  'fedex': 'FDX',
  'ups': 'UPS', 'united parcel service': 'UPS',
  'delta airlines': 'DAL', 'delta air lines': 'DAL',
  'united airlines': 'UAL',
  'american airlines': 'AAL',
  'southwest airlines': 'LUV',
  'uber': 'UBER',
  'lyft': 'LYFT',
  'doordash': 'DASH',
  'airbnb': 'ABNB',
  'booking': 'BKNG', 'booking holdings': 'BKNG',
  'expedia': 'EXPE',
  'marriott': 'MAR',
  'hilton': 'HLT',
  'hyatt': 'H',

  // ===== REITs / Real Estate =====
  'american tower': 'AMT',
  'prologis': 'PLD',
  'crown castle': 'CCI',
  'equinix': 'EQIX',
  'public storage': 'PSA',
  'realty income': 'O',
  'simon property': 'SPG',
  'welltower': 'WELL',

  // ===== Crypto / Fintech =====
  'coinbase': 'COIN',
  'robinhood': 'HOOD',
  'sofi': 'SOFI', 'sofi technologies': 'SOFI',
  'affirm': 'AFRM',
  'upstart': 'UPST',
  'marathon digital': 'MARA',
  'riot platforms': 'RIOT',
  'cleanspark': 'CLSK',
  'microstrategy': 'MSTR',

  // ===== Other notable =====
  'ferrari': 'RACE',
  'lvmh': 'LVMUY',
  'hermes': 'HESAY', 'hermès': 'HESAY',
  'tencent': 'TCEHY',
  'alibaba': 'BABA',
  'jd.com': 'JD', 'jd com': 'JD',
  'pinduoduo': 'PDD',
  'baidu': 'BIDU',
  'samsung': 'SSNLF',
  'sony': 'SONY',
  'nintendo': 'NTDOY',
  'spotify': 'SPOT',
  'plug power': 'PLUG',
  'fuelcell': 'FCEL',
  'enphase': 'ENPH',
  'first solar': 'FSLR',
  'sunrun': 'RUN',
  'sunpower': 'SPWR',
};

// 인기 모니터링 종목 (US Yahoo Finance에서 뉴스 폴링할 종목)
window.US_WATCHLIST_DEFAULT = [
  'AAPL', 'MSFT', 'NVDA', 'GOOGL', 'AMZN', 'META', 'TSLA', 'AVGO', 'AMD', 'NFLX',
  'INTC', 'QCOM', 'PLTR', 'ORCL', 'CRM', 'ADBE', 'CSCO', 'IBM', 'NOW', 'SHOP',
  'COIN', 'TSM', 'ASML', 'MU', 'ARM', 'MRVL', 'SMCI', 'SNOW', 'CRWD', 'NET',
  'LLY', 'NVO', 'JNJ', 'UNH', 'PFE', 'MRNA', 'ABBV', 'TMO', 'DHR', 'ISRG',
  'JPM', 'BAC', 'WFC', 'GS', 'MS', 'V', 'MA', 'BRK.B', 'BLK', 'SCHW',
  'XOM', 'CVX', 'COP', 'OXY', 'NEE',
  'WMT', 'COST', 'HD', 'TGT', 'MCD', 'SBUX', 'KO', 'PEP', 'NKE', 'DIS',
  'BA', 'CAT', 'DE', 'GE', 'HON', 'LMT', 'RTX',
  'UBER', 'LYFT', 'DASH', 'ABNB', 'BKNG',
];

window.extractUSTicker = function(text) {
  const lower = text.toLowerCase();
  const sortedNames = Object.keys(window.US_STOCKS).sort((a, b) => b.length - a.length);
  for (const name of sortedNames) {
    if (lower.includes(name)) {
      return { ticker: window.US_STOCKS[name], name: name.charAt(0).toUpperCase() + name.slice(1) };
    }
  }
  // SEC 형식: "Apple Inc (0000320193)"
  const m = text.match(/- (.+?) \(\d{10}\)/);
  if (m) {
    const company = m[1].trim();
    const lc = company.toLowerCase();
    for (const name of sortedNames) {
      if (lc.includes(name)) {
        return { ticker: window.US_STOCKS[name], name: company };
      }
    }
    // 매칭 안 되는 회사도 그냥 회사명으로 표시
    return { ticker: company.replace(/[^A-Z0-9]/gi, '').slice(0, 10).toUpperCase(), name: company };
  }
  return null;
};
